[package]
name = "l10nregistry-ffi"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
futures-channel = "0.3"
futures = "0.3"
libc = "0.2"
cstr = "0.2"
log = "0.4"
nserror = { path = "../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../xpcom/rust/nsstring" }
l10nregistry = { path = "../l10nregistry-rs" }
fluent = { version = "0.16.0", features = ["fluent-pseudo"] }
unic-langid = "0.9"
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }
async-trait = "0.1"
moz_task = { path = "../../../../xpcom/rust/moz_task" }
xpcom = { path = "../../../../xpcom/rust/xpcom" }
fluent-ffi = { path = "../fluent-ffi" }
fluent-fallback = "0.7.0"
