[package]
name = "l10nregistry-ffi"
version = "0.1.0"
authors = ["nobody@mozilla.org"]
edition = "2018"

[dependencies]
futures-channel = "0.3"
libc = "0.2"
nserror = { path = "../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../xpcom/rust/nsstring" }
