// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Auto-generated by browser/components/aiwindow/models/scripts/generate_prefs_nav_map.py
// Do not edit manually. Run the script to regenerate.

export const PREFERENCES_NAV_MAP = {
  "about:preferences": {
    "label": "Settings",
    "breadcrumb": "Settings",
    "description": null
  },
  "about:preferences#ai": {
    "label": "AI Controls",
    "breadcrumb": "Settings > AI Controls",
    "description": "You always have a choice in Firefox, including whether to use features enhanced with AI. More controls coming soon."
  },
  "about:preferences#dnsOverHttps": {
    "label": "DNS over HTTPS",
    "breadcrumb": "Settings > Browser Privacy > DNS over HTTPS",
    "description": "Domain Name System (DNS) over HTTPS sends your request for a domain name through an encrypted connection, providing a secure DNS and making it harder for others to see which website you’re about to access."
  },
  "about:preferences#etp": {
    "label": "Enhanced Tracking Protection",
    "breadcrumb": "Settings > Browser Privacy > Enhanced Tracking Protection",
    "description": "Sites use trackers to follow you online and show creepy ads. Firefox shields you as you browse, blocking trackers automatically so you’re in control of your digital trail."
  },
  "about:preferences#etpCustomize": {
    "label": "Customize tracking protection",
    "breadcrumb": "Settings > Browser Privacy > Enhanced Tracking Protection > Customize tracking protection",
    "description": null
  },
  "about:preferences#general": {
    "label": "General",
    "breadcrumb": "Settings > General",
    "description": null
  },
  "about:preferences#history": {
    "label": "History",
    "breadcrumb": "Settings > Browser Privacy > History",
    "description": "Choose what you want Firefox to remember when you close the browser."
  },
  "about:preferences#home": {
    "label": "Home and startup",
    "breadcrumb": "Settings > Home and startup",
    "description": null
  },
  "about:preferences#manageAddresses": {
    "label": "Manage addresses and more",
    "breadcrumb": "Settings > Browser Privacy > Manage addresses and more",
    "description": null
  },
  "about:preferences#manageMemories": {
    "label": "Manage memories",
    "breadcrumb": "Settings > AI Controls > Smart Window > Manage memories",
    "description": "Memories are what Smart Window learns from your activity."
  },
  "about:preferences#managePayments": {
    "label": "Manage payment methods",
    "breadcrumb": "Settings > Browser Privacy > Manage payment methods",
    "description": null
  },
  "about:preferences#profiles": {
    "label": "Profiles",
    "breadcrumb": "Settings > Profiles",
    "description": null
  },
  "about:preferences#personalizeSmartWindow": {
    "label": "Smart Window",
    "breadcrumb": "Settings > AI Controls > Smart Window",
    "description": "Choose a model based on what’s important to you."
  },
  "about:preferences#sync": {
    "label": "Account and sync",
    "breadcrumb": "Settings > Account and sync",
    "description": null
  },
  "about:preferences#privacy": {
    "label": "Browser Privacy",
    "breadcrumb": "Settings > Browser Privacy",
    "description": null
  },
  "about:preferences#translations": {
    "label": "More translation settings",
    "breadcrumb": "Settings > General > More translation settings",
    "description": "Translate pages or selected text. To protect your privacy, translations stay on your device."
  }
};
