[package]
name = "cascade_bloom_filter"
version = "0.1.0"
authors = ["Rob Wu <rob@robwu.nl>"]
license = "MPL-2.0"

[dependencies]
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
rust_cascade = "1.4.0"
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }
xpcom = { path = "../../../xpcom/rust/xpcom" }
