# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = []

if buildconfig.substs["OS_ARCH"] == "WINNT":
    Classes += [
        {
            "cid": "{da7de528-7a15-452e-b5a7-521099997ca1}",
            "contract_ids": ["@mozilla.org/browser/windows-default-clh;1"],
            "categories": {
                "command-line-handler": "l-windows-default",
            },
            "esModule": "moz-src:///browser/components/shell/WindowsSetDefaultAppCmdHandler.sys.mjs",
            "constructor": "CommandLineHandler",
        },
    ]
