[autoformat]
# Set `enabled = True/False` to enable/disable Lando automated code formatting.
enabled = True

[lando-prod]
instance_id = lando-prod
api_domain = api.lando.services.mozilla.com

# Lando production Auth0 configuration.
auth0_domain = auth.mozilla.auth0.com
auth0_client_id = ccpmWbDAMz1pxHIWF4vqkdr0ScdgDyyM
auth0_audience = https://api.lando.services.mozilla.com
auth0_scope = openid email profile lando https://sso.mozilla.com/claim/groups

[lando-dev]
instance_id = lando-dev
api_domain = api.dev.lando.nonprod.cloudops.mozgcp.net

# Lando dev server Auth0 configuration.
auth0_domain = auth.mozilla.auth0.com
auth0_client_id = TAtuZwbJd4SRtWg0YznfS1YYCatOvvnX
auth0_audience = https://api.lando.devsvcdev.mozaws.net
auth0_scope = openid email profile lando https://sso.mozilla.com/claim/groups

[lando-prod-new]
instance_id = lando-prod-2025
api_domain = lando.moz.tools

# Lando production Auth0 configuration.
auth0_domain = auth.mozilla.auth0.com
auth0_client_id = ccpmWbDAMz1pxHIWF4vqkdr0ScdgDyyM
auth0_audience = https://lando.moz.tools
auth0_scope = openid email profile lando https://sso.mozilla.com/claim/groups

[lando-dev-new]
instance_id = lando-dev-2025
api_domain = lando-dev.allizom.org

# Lando dev server Auth0 configuration.
auth0_domain = auth.mozilla.auth0.com
auth0_client_id = TAtuZwbJd4SRtWg0YznfS1YYCatOvvnX
auth0_audience = https://lando-dev.allizom.org
auth0_scope = openid email profile lando https://sso.mozilla.com/claim/groups
