/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is a copy of a file that is generated by the chromium build, with only
// the build flags we require and minor changes to set flags based on the build
// and to turn off partition_alloc features to limit dependencies.

// Generated by build/write_buildflag_header.py
// From "//base/allocator/partition_allocator/src/partition_alloc:partition_alloc_buildflags"

#ifndef BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BUILDFLAGS_H_
#define BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#ifdef HAVE_64BIT_BUILD
#define BUILDFLAG_INTERNAL_HAS_64_BIT_POINTERS() (1)
#else
#define BUILDFLAG_INTERNAL_HAS_64_BIT_POINTERS() (0)
#endif  // HAVE_64BIT_BUILD
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (0)
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC_AS_MALLOC() (0)
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_SUPPORT() (0)
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_SLOW_CHECKS() (0)
#define BUILDFLAG_INTERNAL_ENABLE_DANGLING_RAW_PTR_CHECKS() (0)
#define BUILDFLAG_INTERNAL_ENABLE_POINTER_ARITHMETIC_TRAIT_CHECK() (1)
#define BUILDFLAG_INTERNAL_PUT_REF_COUNT_IN_PREVIOUS_SLOT() (1)
#define BUILDFLAG_INTERNAL_USE_ASAN_BACKUP_REF_PTR() (0)
#define BUILDFLAG_INTERNAL_USE_ASAN_UNOWNED_PTR() (0)
#define BUILDFLAG_INTERNAL_USE_HOOKABLE_RAW_PTR() (0)
#define BUILDFLAG_INTERNAL_FORCE_ENABLE_RAW_PTR_EXCLUSION() (0)
#define BUILDFLAG_INTERNAL_ENABLE_POINTER_COMPRESSION() (0)
#define BUILDFLAG_INTERNAL_ENABLE_SHADOW_METADATA_FOR_64_BITS_POINTERS() (0)
#define BUILDFLAG_INTERNAL_USE_STARSCAN() (0)
#define BUILDFLAG_INTERNAL_ENABLE_THREAD_ISOLATION() (0)

#endif  //BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BUILDFLAGS_H_
