/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is a copy of a file that is generated by the chromium build.

// Generated by build/write_buildflag_header.py
// From "//base/allocator/partition_allocator/src/partition_alloc:raw_ptr_buildflags"

#ifndef BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_
#define BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_CONSTRUCT() (1)
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_MOVE() (1)
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_DESTRUCT() (0)

#endif  // BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_

