[worker-dedicated-importscripts.https.sub.html]
  expected:
    if (os == "android") and fission: [OK, TIMEOUT]

  # Header not implemented for Dedicated Worker importScripts (bug 2006421)
  [sec-fetch-storage-access - Cross-site]
    expected: FAIL
