# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{b6d8b8d7-8b81-493d-806d-fb10072e3afd}',
        'contract_ids': ['@mozilla.org/toolkit/picture-in-picture-provider'],
        'esModule': 'moz-src:///browser/components/pictureinpicture/DesktopPictureInPictureProvider.sys.mjs',
        'processes': ProcessSelector.CONTENT_PROCESS_ONLY,
        'constructor': 'PictureInPictureProvider',
    },
]
