[package]
edition = "2021"
name = "geckodriver"
version = "0.34.0"
authors = ["Mozilla"]
include = [
    "/.cargo",
    "/build.rs",
    "/src"
  ]
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
readme = "README.md"
keywords = [
    "firefox",
    "httpd",
    "mozilla",
    "w3c",
    "webdriver",
  ]
license = "MPL-2.0"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver"

[dependencies]
anyhow = "1"
base64 = "0.21"
chrono = "0.4.6"
clap = { version = "4", default-features = false, features = ["cargo", "std", "suggestions", "wrap_help", "string"] }
hyper = "0.14"
icu_segmenter = { version = "1.4", default-features = false, features = ["auto", "compiled_data"] }
lazy_static = "1.0"
log = { version = "0.4", features = ["std"] }
marionette = { path = "./marionette", version="0.5.0" }
mozdevice = { path = "../mozbase/rust/mozdevice", version="0.5.2" }
mozprofile = { path = "../mozbase/rust/mozprofile", version="0.9.2" }
mozrunner = { path = "../mozbase/rust/mozrunner", version="0.15.2" }
mozversion = { path = "../mozbase/rust/mozversion", version="0.5.2" }
regex = { version="1.0", default-features = false, features = ["perf", "std"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tempfile = "3"
thiserror = "1"
url = "2.4"
uuid = { version = "1.0", features = ["v4"] }
webdriver = { path = "../webdriver", version="0.50.0" }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
mozilla-central-workspace-hack = { version = "0.1", features = ["geckodriver"], optional = true }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "geckodriver"
