# is-public-jexl and default-value-jexl are both JEXL expressions.
# They are evaluated using the Experimenter environment, plus some
# additional variables defined by ASRouter and FeatureGate.
# The result of evaluating is-public-jexl is exposed as `isPublic`
# and controls whether the feature is shown to the user in e.g.
# the relevant pane in Firefox's settings.
# The result of evaluating default-value-jexl is exposed as
# `defaultValue` and should match the default value of the pref
# as set in the relevant .js prefs file or StaticPrefList.yaml.

[css-masonry]
title = "experimental-features-css-masonry2"
description = "experimental-features-css-masonry-description"
description-links = {explainer = "https://github.com/w3c/csswg-drafts/blob/master/css-grid-2/MASONRY-EXPLAINER.md", w3c-issue = "https://github.com/w3c/csswg-drafts/issues/4650", bug = "https://bugzilla.mozilla.org/show_bug.cgi?id=1607439"}
restart-required = false
preference = "layout.css.grid-template-masonry-value.enabled"
type = "boolean"
bug-numbers = [1607954]
is-public-jexl = "nightly_build"
default-value-jexl = "nightly_build || thunderbird"

[web-api-webgpu]
title = "experimental-features-web-gpu2"
description = "experimental-features-web-gpu-description3"
description-links = {wikipedia-webgpu = "https://en.wikipedia.org/wiki/WebGPU", wikipedia-gpu = "https://en.wikipedia.org/wiki/Graphics_processing_unit", spec = "https://gpuweb.github.io/gpuweb/", bugzilla = "https://bugzilla.mozilla.org/show_bug.cgi?id=1616739"}
restart-required = false
preference = "dom.webgpu.enabled"
type = "boolean"
bug-numbers = [1616739]
is-public-jexl = "nightly_build"
default-value-jexl = "nightly_build"

[media-jxl]
title = "experimental-features-media-jxl"
description = "experimental-features-media-jxl-description"
description-links = {bugzilla = "https://bugzilla.mozilla.org/show_bug.cgi?id=1539075"}
restart-required = false
preference = "image.jxl.enabled"
type = "boolean"
bug-numbers = [1539075]
is-public-jexl = "nightly_build"
default-value-jexl = "false"

[cookie-samesite-none-requires-secure]
title = "experimental-features-cookie-samesite-none-requires-secure2"
description = "experimental-features-cookie-samesite-none-requires-secure2-description"
restart-required = false
preference = "network.cookie.sameSite.noneRequiresSecure"
type = "boolean"
bug-numbers = [1618610, 1617609]
is-public-jexl = "false"
default-value-jexl = "nightly_build"

[devtools-serviceworker-debugger-support]
title = "experimental-features-devtools-serviceworker-debugger-support"
description = "experimental-features-devtools-serviceworker-debugger-support-description"
restart-required = true
preference = "devtools.debugger.features.windowless-service-workers"
type = "boolean"
bug-numbers = [1651607]
is-public-jexl = "true"
default-value-jexl = "false"

[genai-chat]
title = "genai-settings-chat-title"
description = "genai-settings-chat-description"
# Bug 1895497 to add actual link
description-links = {connect= "https://connect.mozilla.org"}
restart-required = false
preference = "browser.ml.chat.enabled"
type = "boolean"
bug-numbers = [1894999]
is-public-jexl = "false"
default-value-jexl = "false"

[webrtc-global-mute-toggles]
title = "experimental-features-webrtc-global-mute-toggles"
description = "experimental-features-webrtc-global-mute-toggles-description"
restart-required = false
preference = "privacy.webrtc.globalMuteToggles"
type = "boolean"
bug-numbers = [1643027]
is-public-jexl = "nightly_build"
default-value-jexl = "false"

[url-bar-ime-search]
title = "experimental-features-ime-search"
description = "experimental-features-ime-search-description"
restart-required = false
preference = "browser.urlbar.keepPanelOpenDuringImeComposition"
type = "boolean"
bug-numbers = [1673971]
is-public-jexl = "true"
default-value-jexl = "false"
