# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{ebe8a51d-bd54-4838-b031-cd2289990e14}',
        'contract_ids': ['@mozilla.org/webauthn/service;1'],
        'headers': ['/dom/webauthn/WebAuthnService.h'],
        'constructor': 'mozilla::dom::NewWebAuthnService',
    },
    {
        'cid': '{922594a0-1bd9-4a92-8d68-f308d6ce8982}',
        'contract_ids': ['@mozilla.org/webauthn/related-origin-fetcher;1'],
        'esModule': 'resource://gre/modules/WebAuthnRelatedOriginFetcher.sys.mjs',
        'constructor': 'WebAuthnRelatedOriginFetcher',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
