[package]
name = "mdns_service"
version = "0.1.1"
authors = ["Dan Minor <dminor@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
byteorder = "1.3.1"
dns-parser = "0.8.0"
gecko-profiler = { path = "../../../../../tools/profiler/rust-api" }
log = "0.4"
socket2 = { version = "0.4", features = ["all"] }
uuid = { version = "1.0", features = ["v4"] }
