# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Gradle and Android Studio will search org.gradle.java.installations.paths
# and JAVA_HOME for a JDK whose major version matches the value below
# to run the Gradle daemon.
toolchainVersion=17
