[package]
name = "mozurl"
version = "0.0.1"
authors = ["Nika Layzell <nika@thelayzells.com>"]
license = "MPL-2.0"

[dependencies]
url = "2.0"
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
xpcom = { path = "../../../xpcom/rust/xpcom" }
uuid = { version = "1.0", features = ["v4"] }
