# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import buildconfig
import mozpack.path as mozpath
import sys

sys.path.insert(0, mozpath.join(buildconfig.topsrcdir, "servo", "components", "style", "gecko"))

from pseudo_elements import PseudoElementData

def generate(output):
    data = PseudoElementData()
    output.write(
        """/* THIS IS AN AUTOGENERATED FILE.  DO NOT EDIT */

/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef CSS_PSEUDO_STYLE_TYPE
#define CSS_PSEUDO_STYLE_TYPE(name, flags) /* nothing */
#define DEFINED_CSS_PSEUDO_STYLE_TYPE
#endif

#ifndef CSS_NON_INHERITING_ANON_BOX
#define CSS_NON_INHERITING_ANON_BOX(name, flags) CSS_PSEUDO_STYLE_TYPE(name, flags)
#define DEFINED_CSS_NON_INHERITING_ANON_BOX
#endif

#ifndef CSS_INHERITING_ANON_BOX
#define CSS_INHERITING_ANON_BOX(name, flags) CSS_PSEUDO_STYLE_TYPE(name, flags)
#define DEFINED_CSS_INHERITING_ANON_BOX
#endif

#ifndef CSS_PSEUDO_ELEMENT
#define CSS_PSEUDO_ELEMENT(name, flags) CSS_PSEUDO_STYLE_TYPE(name, flags)
#define DEFINED_CSS_PSEUDO_ELEMENT
#endif
"""
  )

    for pseudo in data.all_pseudos():
        flags = ' | '.join(f"PseudoStyleTypeFlags::{flag}" for flag in pseudo.flags())
        macro_name = "CSS_PSEUDO_ELEMENT"
        if pseudo.is_non_inheriting_anon_box():
            macro_name = "CSS_NON_INHERITING_ANON_BOX"
        elif pseudo.is_inheriting_anon_box():
            macro_name = "CSS_INHERITING_ANON_BOX"
        output.write(f"{macro_name}({pseudo.capitalized}, {flags})\n")

    output.write("""
#ifdef DEFINED_CSS_PSEUDO_STYLE_TYPE
#undef CSS_PSEUDO_STYLE_TYPE
#undef DEFINED_CSS_PSEUDO_STYLE_TYPE
#endif
#ifdef DEFINED_CSS_NON_INHERITING_ANON_BOX
#undef CSS_NON_INHERITING_ANON_BOX
#undef DEFINED_CSS_NON_INHERITING_ANON_BOX
#endif
#ifdef DEFINED_CSS_INHERITING_ANON_BOX
#undef CSS_INHERITING_ANON_BOX
#undef DEFINED_CSS_INHERITING_ANON_BOX
#endif
#ifdef DEFINED_CSS_PSEUDO_ELEMENT
#undef CSS_PSEUDO_ELEMENT
#undef DEFINED_CSS_PSEUDO_ELEMENT
#endif
""")

    return set(data.path_dependencies)
