# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
name: raptor
manifest: testing/raptor/raptor/raptor.ini
static-only: False
suites:
    desktop:
        description: "Tests for page-load performance. The links direct to the actual websites that are being tested. (WX: WebExtension, BT: Browsertime, FF: Firefox, CH: Chrome, CU: Chromium)"
        tests:
            raptor-tp6-amazon: "WX, FF, CH, CU"
            raptor-tp6-cnn-ampstories: "WX, FF"
            raptor-tp6-facebook: "WX, CH, CU"
            raptor-tp6-google: "WX, FF, CH, CU"
            raptor-tp6-youtube: "WX, FF, CH, CU"
            raptor-tp6-docs: "WX, FF, CH, CU"
            raptor-tp6-sheets: "WX, FF, CH, CU"
            raptor-tp6-slides: "WX, FF, CH, CU"
            raptor-tp6-imdb: "WX, FF, CH, CU"
            raptor-tp6-imgur: "WX, FF, CH, CU"
            raptor-tp6-fandom: "WX, FF, CH, CU"
            raptor-tp6-bing: "WX, FF, CH, CU"
            raptor-tp6-yandex: "WX, FF, CH, CU"
            raptor-tp6-twitch: "WX, FF, CH, CU"
            raptor-tp6-apple: "WX, FF, CH, CU"
            raptor-tp6-microsoft: "WX, FF, CH, CU"
            raptor-tp6-reddit: "WX, FF, CH, CU"
            raptor-tp6-yahoo-news: "WX, FF, CH, CU"
            raptor-tp6-netflix: "WX, FF, CH, CU"
            raptor-tp6-instagram: "WX, FF, CH, CU"
            raptor-tp6-twitter: "WX, FF, CH, CU"
            raptor-tp6-yahoo-mail: "WX, FF, CH, CU"
            raptor-tp6-ebay: "WX, FF, CH, CU"
            raptor-tp6-linkedin: "WX, FF, CH, CU"
            raptor-tp6-wikipedia: "WX, FF, CH, CU"
            raptor-tp6-google-mail: "WX, FF, CH, CU"
            raptor-tp6-office: "WX, FF, CH, CU"
            raptor-tp6-outlook: "WX, FF, CH, CU"
            raptor-tp6-pinterest: "WX, FF, CH, CU"
            raptor-tp6-paypal: "WX, FF, CH, CU"
            raptor-tp6-tumblr: "WX, FF, CH, CU"
            amazon: "BT, FF, CH, CU"
            apple: "BT, FF, CH, CU"
            bing-search: "BT, FF, CH, CU"
            ebay: "BT, FF, CH, CU"
            facebook: "BT, FF, CH, CU"
            facebook-redesign: "BT, FF, CH, CU"
            fandom: "BT, FF, CH, CU"
            google-docs: "BT, FF, CH, CU"
            google-mail: "BT, FF, CH, CU"
            google-search: "BT, FF, CH, CU"
            google-sheets: "BT, FF, CH, CU"
            google-slides: "BT, FF, CH, CU"
            imdb: "BT, FF, CH, CU"
            imgur: "BT, FF, CH, CU"
            instagram: "BT, FF, CH, CU"
            linkedin: "BT, FF, CH, CU"
            microsoft: "BT, FF, CH, CU"
            netflix: "BT, FF, CH, CU"
            office: "BT, FF, CH, CU"
            outlook: "BT, FF, CH, CU"
            paypal: "BT, FF, CH, CU"
            pinterest: "BT, FF, CH, CU"
            reddit: "BT, FF, CH, CU"
            tumblr: "BT, FF, CH, CU"
            twitch: "BT, FF, CH, CU"
            twitter: "BT, FF, CH, CU"
            wikipedia: "BT, FF, CH, CU"
            yahoo-mail: "BT, FF, CH, CU"
            yahoo-news: "BT, FF, CH, CU"
            yandex: "BT, FF, CH, CU"
            youtube: "BT, FF, CH, CU"
    mobile:
        description: "Page-load performance test suite on Android. The links direct to the actual websites that are being tested. (WX: WebExtension, BT: Browsertime, GV: Geckoview, RB: Refbrow, FE: Fenix, F68: Fennec68, CH-M: Chrome mobile)"
        tests:
            amazon: "BT, GV, FE, RB, F68, CH-M"
            youtube: "BT, GV, FE, RB, F68, CH-M"
            allrecipes: "BT, GV, FE, RB, F68, CH-M"
            amazon-search: "BT, GV, FE, RB, F68, CH-M"
            bbc: "BT, GV, FE, RB, F68, CH-M"
            bing: "BT, GV, FE, RB, F68, CH-M"
            bing-search-restaurants: "BT, GV, FE, RB, F68, CH-M"
            booking: "BT, GV, FE, RB, F68, CH-M"
            cnn: "BT, GV, FE, RB, F68, CH-M"
            cnn-ampstories: "BT, GV, FE, RB, F68, CH-M"
            ebay-kleinanzeigen: "BT, GV, FE, RB, F68, CH-M"
            ebay-kleinanzeigen-search: "BT, GV, FE, RB, F68, CH-M"
            espn: "BT, GV, FE, RB, F68, CH-M"
            facebook: "BT, GV, FE, RB, F68, CH-M"
            facebook-cristiano: "BT, GV, FE, RB, F68, CH-M"
            google: "BT, GV, FE, RB, F68, CH-M"
            google-maps: "BT, GV, FE, RB, F68, CH-M"
            google-search-restaurants: "BT, GV, FE, RB, F68, CH-M"
            imdb: "BT, GV, FE, RB, F68, CH-M"
            instagram: "BT, GV, FE, RB, F68, CH-M"
            jianshu: "BT, GV, FE, RB, F68, CH-M"
            microsoft-support: "BT, GV, FE, RB, F68, CH-M"
            reddit: "BT, GV, FE, RB, F68, CH-M"
            stackoverflow: "BT, GV, FE, RB, F68, CH-M"
            web-de: "BT, GV, FE, RB, F68, CH-M"
            wikipedia: "BT, GV, FE, RB, F68, CH-M"
            youtube-watch: "BT, GV, FE, RB, F68, CH-M"
    live:
        description: "A set of test pages that are run as live sites instead of recorded versions. These tests are available on all browsers, on all platforms."
    benchmarks:
        description: "Standard benchmarks are third-party tests (i.e. Speedometer) that we have integrated into Raptor to run per-commit in our production CI. "
    scenario:
        description: "Tests that perform a specific action (a scenario), i.e. idle application, idle application in background, etc."
    unittests:
        description: "These tests aren't used in standard testing, they are only used in the Raptor unit tests (they are similar to raptor-tp6 tests though)."
