[package]
name = "dap_ffi-gtest"
version = "0.1.0"
authors = [
    "Simon Friedberger <simon@mozilla.com>",
]
license = "MPL-2.0"
description = "Tests for Rust code for DAP; mainly encoding and NSS bindings."
edition = "2021"

[dependencies]
dap_ffi = { path = "../ffi" }
hex = { version = "0.4.3", features = ["serde"] }
prio = {version = "0.9.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }

[lib]
path = "test.rs"
