[package]
name = "kvstore"
version = "0.1.0"
authors = ["Myk Melez <myk@mykzilla.org>"]

[dependencies]
atomic_refcell = "0.1"
crossbeam-utils = "0.6.3"
cstr = "0.1"
lazy_static = "1"
libc = "0.2"
lmdb-rkv = "0.14"
log = "0.4"
moz_task = { path = "../../../xpcom/rust/moz_task" }
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
rkv = { version = "0.15.0", default-features = false, features=["no-canonicalize-path"] }
storage_variant = { path = "../../../storage/variant" }
xpcom = { path = "../../../xpcom/rust/xpcom" }
tempfile = "3"
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }

# Get rid of failure's dependency on backtrace. Eventually
# backtrace will move into Rust core, but we don't need it here.
[dependencies.failure]
version = "0.1"
default_features = false
features = ["derive"]
