/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(9EF7D210-267C-4972-B9D6-88AEAB955441)]
interface nsISound : nsISupports
{
  void beep();

  /**
    * Not strictly necessary, but avoids delay before first sound.
    * The various methods on nsISound call Init() if they need to.
    */
  void init();

  /**
   * In some situations, playEventSound will be called.  Then, each
   * implementations will play a system sound for the event if it's necessary.
   */
  const unsigned long EVENT_NEW_MAIL_RECEIVED           = 0;
  const unsigned long EVENT_ALERT_DIALOG_OPEN           = 1;
  const unsigned long EVENT_CONFIRM_DIALOG_OPEN         = 2;
  const unsigned long EVENT_PROMPT_DIALOG_OPEN          = 3;
  const unsigned long EVENT_SELECT_DIALOG_OPEN          = 4;
  const unsigned long EVENT_MENU_EXECUTE                = 5;
  const unsigned long EVENT_MENU_POPUP                  = 6;
  const unsigned long EVENT_EDITOR_MAX_LEN              = 7;
  void playEventSound(in unsigned long aEventId);
};
