# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{C7DDDBF2-8BC4-41A1-AC90-5144BEC5ABDF}',
        'contract_ids': ['@mozilla.org/content-classifier-rs-client;1'],
        'esModule': 'resource://gre/modules/ContentClassifierRemoteSettingsClient.sys.mjs',
        'constructor': 'ContentClassifierRemoteSettingsClient',
        'singleton': True,
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
