# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

pages = [
    'home',
    'newtab',
]

Classes = [
    {
        'cid': '{08ab87cc-95c2-4e67-885c-12bb7a146eea}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=%s' % page
                         for page in pages],
        'esModule': 'resource:///modules/AboutNewTabRedirector.sys.mjs',
        'constructor': 'AboutNewTabRedirectorStub',
    },
    {
        'cid': '{04cb5d8f-a76b-49c1-b265-93b0a6e57302}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=moz-newtab-remote-renderer'],
        "esModule": "moz-src:///browser/components/newtab/MozNewTabRemoteRendererProtocolHandler.sys.mjs",
        'constructor': "MozNewTabRemoteRendererProtocolHandler",
        'protocol_config': {
            'scheme': 'moz-newtab-remote-renderer',
            'flags': [
                'URI_STD',
                'URI_IS_LOCAL_RESOURCE',
                'URI_IS_POTENTIALLY_TRUSTWORTHY',
                'URI_IS_UI_RESOURCE',
            ],
        },
    },

]
