/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is a copy of a file that is generated by the chromium build, with
// only the build flags we require.

// Generated by build/write_buildflag_header.py
// From "//base/win:base_win_buildflags"

#ifndef BASE_WIN_BASE_WIN_BUILDFLAGS_H_
#define BASE_WIN_BASE_WIN_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_SINGLE_MODULE_MODE_HANDLE_VERIFIER() (0)

#endif  // BASE_WIN_BASE_WIN_BUILDFLAGS_H_
