[package]
name = "authrs_bridge"
version = "0.1.0"
edition = "2021"
authors = ["Martin Sirringhaus", "John Schanck"]

[dependencies]
authenticator = { version = "0.4.0-alpha.24", features = ["gecko"] }
base64 = "^0.21"
cstr = "0.2"
log = "0.4"
moz_task = { path = "../../../xpcom/rust/moz_task" }
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"
static_prefs = { path = "../../../modules/libpref/init/static_prefs" }
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }
xpcom = { path = "../../../xpcom/rust/xpcom" }

[features]
fuzzing = []
