/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is a copy of a file that is generated by the chromium build, with only
// the build flags we require and minor changes to set flags based on the build.

// Generated by build/write_buildflag_header.py
// From "//base/allocator/partition_allocator/src/partition_alloc:debugging_buildflags"

#ifndef BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_
#define BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#if defined(NDEBUG) && !defined(DCHECK_ALWAYS_ON)
#define BUILDFLAG_INTERNAL_PA_DCHECK_IS_ON() (0)
#else
#define BUILDFLAG_INTERNAL_PA_DCHECK_IS_ON() (1)
#endif
#define BUILDFLAG_INTERNAL_PA_EXPENSIVE_DCHECKS_ARE_ON() (1)
#define BUILDFLAG_INTERNAL_PA_DCHECK_IS_CONFIGURABLE() (0)


#endif  // BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_PARTITION_ALLOC_BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_
