[package]
name = "jog"
version = "0.1.0"
authors = ["Glean SDK team <glean-team@mozilla.com>"]
edition = "2021"
publish = false
license = "MPL-2.0"

[dependencies]
firefox-on-glean = { path = "../../api" }
log = "0.4"
mozbuild = "0.1"
nsstring = { path = "../../../../../xpcom/rust/nsstring", optional = true }
once_cell = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }

[features]
with_gecko = [ "nsstring" ]
