[DEFAULT]
subsuite = "webgpu"
run-if = ["!release_or_beta"]
prefs = [
  "dom.webgpu.enabled=true",
  "dom.webgpu.workers.enabled=true",
  "gfx.offscreencanvas.enabled=true",
]
support-files = [
  "worker_wrapper.js",
  "test_basic_canvas.worker.js",
  "test_submit_render_empty.worker.js",
]

# WebGPU is only available in secure contexts.
#
# See spec WebIDL, like this: https://www.w3.org/TR/webgpu/#navigatorgpu
scheme = "https"

["test_basic_canvas.worker.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_buffer_mapping.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_buffer_mapping_invalid_device.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_command_buffer_creation.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_context_configure.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_device_creation.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_device_lost.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_double_encoder_finish.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_enabled.html"]

["test_error_scope.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_insecure_context.html"]
# This test checks that WebGPU is not available in insecure contexts.
scheme = "http"

["test_navigator_gpu_not_replaceable.html"]

["test_queue_copyExternalImageToTexture.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_queue_write.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_queue_write_invalid_device.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_submit_compute_empty.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_submit_render_empty.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]

["test_submit_render_empty.worker.html"]
fail-if = [
  "os == 'linux' && os_version == '18.04'",
  "os == 'mac'",
]
