[package]
name = "fog_control"
version = "0.1.0"
authors = ["Glean SDK team <glean-team@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
glean = "56.1.0"
log = "0.4"
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
static_prefs = { path = "../../../modules/libpref/init/static_prefs" }
xpcom = { path = "../../../xpcom/rust/xpcom" }
once_cell = "1.2.0"
firefox-on-glean = { path = "./api" }
cstr = "0.2"
viaduct = "0.1"
url = "2.1"
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }

[features]
# Leave data collection enabled, but disable upload.
disable_upload = []
# Letting us know we're compiling with Gecko symbols.
with_gecko = ["firefox-on-glean/with_gecko"]
# Opt into a larger preinit queue
million_queue = ["glean/preinit_million_queue"]
