[advisories]
ignore = [
  # bincode <https://bugzilla.mozilla.org/show_bug.cgi?id=2011119>
  "RUSTSEC-2025-0141",
  # remove_dir_all <https://bugzilla.mozilla.org/show_bug.cgi?id=1975554>
  "RUSTSEC-2023-0018",
  # paste <https://bugzilla.mozilla.org/show_bug.cgi?id=1998421>
  "RUSTSEC-2024-0436",
]
