# https://bugzilla.mozilla.org/show_bug.cgi?id=926940
prefs:
  if os=="android": [dom.webserial.enabled:false]
  [dom.webserial.enabled:true, dom.security.featurePolicy.header.enabled:true, dom.security.featurePolicy.webidl.enabled:true]