[package]
name = "data-encoding-ffi"
version = "0.1.0"
license = "MPL-2.0"
authors = ["The Mozilla Project Developers"]

[dependencies]
data-encoding = "2.2.1"
nsstring = { path = "../../../../../xpcom/rust/nsstring" }
