[package]
name = "moz_task"
version = "0.1.0"
authors = ["Myk Melez <myk@mykzilla.org>"]
license = "MPL-2.0"
description = "Rust wrappers around XPCOM threading functions"
edition = "2018"

[dependencies]
log = "0.4"
cstr = "0.2"
libc = "0.2"
async-task = { version = "4.3" }
nserror = { path = "../nserror" }
nsstring = { path = "../nsstring" }
xpcom = { path = "../xpcom" }
