/* Generated by wayland-scanner 1.19.0 */

#ifndef XX_SESSION_MANAGEMENT_V1_CLIENT_PROTOCOL_H
#define XX_SESSION_MANAGEMENT_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef __cplusplus
extern "C" {
#endif

struct xdg_toplevel;
struct xx_session_manager_v1;
struct xx_session_v1;
struct xx_toplevel_session_v1;

#ifndef XX_SESSION_MANAGER_V1_INTERFACE
#  define XX_SESSION_MANAGER_V1_INTERFACE
extern const struct wl_interface xx_session_manager_v1_interface;
#endif
#ifndef XX_SESSION_V1_INTERFACE
#  define XX_SESSION_V1_INTERFACE
extern const struct wl_interface xx_session_v1_interface;
#endif
#ifndef XX_TOPLEVEL_SESSION_V1_INTERFACE
#  define XX_TOPLEVEL_SESSION_V1_INTERFACE
extern const struct wl_interface xx_toplevel_session_v1_interface;
#endif

#ifndef XX_SESSION_MANAGER_V1_ERROR_ENUM
#  define XX_SESSION_MANAGER_V1_ERROR_ENUM
enum xx_session_manager_v1_error {
  XX_SESSION_MANAGER_V1_ERROR_IN_USE = 1,
};
#endif /* XX_SESSION_MANAGER_V1_ERROR_ENUM */

#ifndef XX_SESSION_MANAGER_V1_REASON_ENUM
#  define XX_SESSION_MANAGER_V1_REASON_ENUM
enum xx_session_manager_v1_reason {
  XX_SESSION_MANAGER_V1_REASON_LAUNCH = 1,
  XX_SESSION_MANAGER_V1_REASON_RECOVER = 2,
  XX_SESSION_MANAGER_V1_REASON_SESSION_RESTORE = 3,
};
#endif /* XX_SESSION_MANAGER_V1_REASON_ENUM */

#define XX_SESSION_MANAGER_V1_DESTROY 0
#define XX_SESSION_MANAGER_V1_GET_SESSION 1

#define XX_SESSION_MANAGER_V1_DESTROY_SINCE_VERSION 1
#define XX_SESSION_MANAGER_V1_GET_SESSION_SINCE_VERSION 1

/** @ingroup iface_xx_session_manager_v1 */
static inline void xx_session_manager_v1_set_user_data(
    struct xx_session_manager_v1* xx_session_manager_v1, void* user_data) {
  wl_proxy_set_user_data((struct wl_proxy*)xx_session_manager_v1, user_data);
}

/** @ingroup iface_xx_session_manager_v1 */
static inline void* xx_session_manager_v1_get_user_data(
    struct xx_session_manager_v1* xx_session_manager_v1) {
  return wl_proxy_get_user_data((struct wl_proxy*)xx_session_manager_v1);
}

static inline uint32_t xx_session_manager_v1_get_version(
    struct xx_session_manager_v1* xx_session_manager_v1) {
  return wl_proxy_get_version((struct wl_proxy*)xx_session_manager_v1);
}

static inline void xx_session_manager_v1_destroy(
    struct xx_session_manager_v1* xx_session_manager_v1) {
  wl_proxy_marshal((struct wl_proxy*)xx_session_manager_v1,
                   XX_SESSION_MANAGER_V1_DESTROY);

  wl_proxy_destroy((struct wl_proxy*)xx_session_manager_v1);
}

static inline struct xx_session_v1* xx_session_manager_v1_get_session(
    struct xx_session_manager_v1* xx_session_manager_v1, uint32_t reason,
    const char* session) {
  struct wl_proxy* id;

  id = wl_proxy_marshal_constructor((struct wl_proxy*)xx_session_manager_v1,
                                    XX_SESSION_MANAGER_V1_GET_SESSION,
                                    &xx_session_v1_interface, NULL, reason,
                                    session);

  return (struct xx_session_v1*)id;
}

/* xx_session_v1 */

#ifndef XX_SESSION_V1_ERROR_ENUM
#  define XX_SESSION_V1_ERROR_ENUM
enum xx_session_v1_error {
  XX_SESSION_V1_ERROR_INVALID_RESTORE = 1,
  XX_SESSION_V1_ERROR_NAME_IN_USE = 2,
  XX_SESSION_V1_ERROR_ALREADY_MAPPED = 3,
};
#endif /* XX_SESSION_V1_ERROR_ENUM */

struct xx_session_v1_listener {
  void (*created)(void* data, struct xx_session_v1* xx_session_v1,
                  const char* id);
  void (*restored)(void* data, struct xx_session_v1* xx_session_v1);
  void (*replaced)(void* data, struct xx_session_v1* xx_session_v1);
};

static inline int xx_session_v1_add_listener(
    struct xx_session_v1* xx_session_v1,
    const struct xx_session_v1_listener* listener, void* data) {
  return wl_proxy_add_listener((struct wl_proxy*)xx_session_v1,
                               (void (**)(void))listener, data);
}

#define XX_SESSION_V1_DESTROY 0
#define XX_SESSION_V1_REMOVE 1
#define XX_SESSION_V1_ADD_TOPLEVEL 2
#define XX_SESSION_V1_RESTORE_TOPLEVEL 3

#define XX_SESSION_V1_CREATED_SINCE_VERSION 1
#define XX_SESSION_V1_RESTORED_SINCE_VERSION 1
#define XX_SESSION_V1_REPLACED_SINCE_VERSION 1

#define XX_SESSION_V1_DESTROY_SINCE_VERSION 1
#define XX_SESSION_V1_REMOVE_SINCE_VERSION 1
#define XX_SESSION_V1_ADD_TOPLEVEL_SINCE_VERSION 1
#define XX_SESSION_V1_RESTORE_TOPLEVEL_SINCE_VERSION 1

/** @ingroup iface_xx_session_v1 */
static inline void xx_session_v1_set_user_data(
    struct xx_session_v1* xx_session_v1, void* user_data) {
  wl_proxy_set_user_data((struct wl_proxy*)xx_session_v1, user_data);
}

/** @ingroup iface_xx_session_v1 */
static inline void* xx_session_v1_get_user_data(
    struct xx_session_v1* xx_session_v1) {
  return wl_proxy_get_user_data((struct wl_proxy*)xx_session_v1);
}

static inline uint32_t xx_session_v1_get_version(
    struct xx_session_v1* xx_session_v1) {
  return wl_proxy_get_version((struct wl_proxy*)xx_session_v1);
}

static inline void xx_session_v1_destroy(struct xx_session_v1* xx_session_v1) {
  wl_proxy_marshal((struct wl_proxy*)xx_session_v1, XX_SESSION_V1_DESTROY);

  wl_proxy_destroy((struct wl_proxy*)xx_session_v1);
}

static inline void xx_session_v1_remove(struct xx_session_v1* xx_session_v1) {
  wl_proxy_marshal((struct wl_proxy*)xx_session_v1, XX_SESSION_V1_REMOVE);

  wl_proxy_destroy((struct wl_proxy*)xx_session_v1);
}

static inline struct xx_toplevel_session_v1* xx_session_v1_add_toplevel(
    struct xx_session_v1* xx_session_v1, struct xdg_toplevel* toplevel,
    const char* name) {
  struct wl_proxy* id;

  id = wl_proxy_marshal_constructor(
      (struct wl_proxy*)xx_session_v1, XX_SESSION_V1_ADD_TOPLEVEL,
      &xx_toplevel_session_v1_interface, NULL, toplevel, name);

  return (struct xx_toplevel_session_v1*)id;
}

static inline struct xx_toplevel_session_v1* xx_session_v1_restore_toplevel(
    struct xx_session_v1* xx_session_v1, struct xdg_toplevel* toplevel,
    const char* name) {
  struct wl_proxy* id;

  id = wl_proxy_marshal_constructor(
      (struct wl_proxy*)xx_session_v1, XX_SESSION_V1_RESTORE_TOPLEVEL,
      &xx_toplevel_session_v1_interface, NULL, toplevel, name);

  return (struct xx_toplevel_session_v1*)id;
}

/* xx_toplevel_session_v1 */

struct xx_toplevel_session_v1_listener {
  void (*restored)(void* data,
                   struct xx_toplevel_session_v1* xx_toplevel_session_v1,
                   struct xdg_toplevel* surface);
};

static inline int xx_toplevel_session_v1_add_listener(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1,
    const struct xx_toplevel_session_v1_listener* listener, void* data) {
  return wl_proxy_add_listener((struct wl_proxy*)xx_toplevel_session_v1,
                               (void (**)(void))listener, data);
}

#define XX_TOPLEVEL_SESSION_V1_DESTROY 0
#define XX_TOPLEVEL_SESSION_V1_REMOVE 1

#define XX_TOPLEVEL_SESSION_V1_RESTORED_SINCE_VERSION 1

#define XX_TOPLEVEL_SESSION_V1_DESTROY_SINCE_VERSION 1
#define XX_TOPLEVEL_SESSION_V1_REMOVE_SINCE_VERSION 1

/** @ingroup iface_xx_toplevel_session_v1 */
static inline void xx_toplevel_session_v1_set_user_data(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1, void* user_data) {
  wl_proxy_set_user_data((struct wl_proxy*)xx_toplevel_session_v1, user_data);
}

/** @ingroup iface_xx_toplevel_session_v1 */
static inline void* xx_toplevel_session_v1_get_user_data(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1) {
  return wl_proxy_get_user_data((struct wl_proxy*)xx_toplevel_session_v1);
}

static inline uint32_t xx_toplevel_session_v1_get_version(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1) {
  return wl_proxy_get_version((struct wl_proxy*)xx_toplevel_session_v1);
}

static inline void xx_toplevel_session_v1_destroy(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1) {
  wl_proxy_marshal((struct wl_proxy*)xx_toplevel_session_v1,
                   XX_TOPLEVEL_SESSION_V1_DESTROY);

  wl_proxy_destroy((struct wl_proxy*)xx_toplevel_session_v1);
}

static inline void xx_toplevel_session_v1_remove(
    struct xx_toplevel_session_v1* xx_toplevel_session_v1) {
  wl_proxy_marshal((struct wl_proxy*)xx_toplevel_session_v1,
                   XX_TOPLEVEL_SESSION_V1_REMOVE);

  wl_proxy_destroy((struct wl_proxy*)xx_toplevel_session_v1);
}

#ifdef __cplusplus
}
#endif

#endif
