/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is a copy of a file that is generated by the chromium build.

// Generated by build/write_buildflag_header.py
// From "//base:ios_cronet_buildflags"

#ifndef BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_
#define BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_CRONET_BUILD() (0)

#endif  // BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_
