[package]
name = "mozwer_s"
version = "0.1.0"
authors = ["Gabriele Svelto <gsvelto@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
libc = "0.2.0"
mozilla-central-workspace-hack = { version = "0.1", features = ["mozwer_s"], optional = true }
process_reader = { path = "../process_reader/" }
rust-ini = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
uuid = { version = "1.0", features = ["v4"] }

[dependencies.windows-sys]
version = "0.52"
features = [
    "Wdk_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_ErrorReporting",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[lib]
name = "mozwer_s"
crate-type = ["staticlib"]
path = "lib.rs"
