/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{C++
#include "mozilla/dom/MimeType.h"
%}

native MimeTypeRef(RefPtr<TMimeType<char>>);

[uuid(036d5cd7-9a53-40e3-9c72-c2ffaa15aa2b)]
interface nsIBaseChannel : nsISupports {

  /**
   * Used by fetch and XMLHttpRequest to get the standards-compliant value they
   * should set for the Content-Type header on response (if nullptr, they will
   * use Firefox-specific values from nsIChannel::GetContentType and GetCharset).
   */
  attribute MimeTypeRef fullMimeType;

%{C++
  RefPtr<CMimeType> FullMimeType() {
    RefPtr<CMimeType> type;
    (void)GetFullMimeType(&type);
    return type;
  }
%}

};
