[[repos]]
name = 'spec'
commit = 'f500d7fbb'

[[repos]]
name = 'custom-page-sizes'
commit = '27e2a5fe6'

[[repos]]
name = 'compact-import-section'
commit = 'baa86dc09'

[[repos]]
name = 'stack-switching'
commit = '8fe7145d2'

[[repos]]
name = 'threads'
commit = '979d0fcb9'
