[[repos]]
name = 'spec'
commit = 'b1fbe1a89'

[[repos]]
name = 'threads'
commit = '85b562cd'

[[repos]]
name = 'simd'
commit = 'a78b98a6'

[[repos]]
name = 'memory64'
commit = '8d8f532d3'

[[repos]]
name = 'relaxed-simd'
commit = '22257c57b'

[[repos]]
name = 'extended-const'
commit = '7612271a7'

[[repos]]
name = 'tail-call'
commit = '6f44ca27a'

[[repos]]
name = 'multi-memory'
commit = 'c2c00d81c'

[[repos]]
name = 'function-references'
commit = 'eab6b36ca'

[[repos]]
name = 'exception-handling'
commit = '98e4eb60d'

[[repos]]
name = 'gc'
commit = '207333efd'
