[pointerlock_unadjustedMovement_update.html]
  expected:
    # Not every platform supports unadjusted movement.
    if os == "mac": OK
    if os == "win": OK
    ERROR

  [request pointer lock with different unadjustedMovement on the same locked element should still fire pointerlockchange event]
    expected:
      # Not every platform supports unadjusted movement.
      if os == "mac": PASS
      if os == "win": PASS
      FAIL

  [request pointer lock with different unadjustedMovement on the different element should still fire pointerlockchange event]
    expected:
      # Not every platform supports unadjusted movement.
      if os == "mac": PASS
      if os == "win": PASS
      FAIL
