# See https://bugzilla.mozilla.org/show_bug.cgi?id=1255338#c32.
prefs: [dom.pointer-lock.reset-to-center-from-parent.enabled:true]
[pointerlock-maintains-mousedown.html?unadjustedmovement=true]
  expected:
    # Not every platform supports unadjusted movement.
    if os == "mac": OK
    if os == "win": OK
    ERROR
  [Tests that mousemove events during pointer lock report correct button state]
    expected:
      if os == "linux": FAIL
      if os == "android": FAIL
