[pointerlock-maintains-mousedown.html?unadjustedmovement=true]
  expected:
    # Not every platform supports unadjusted movement.
    if os == "mac": OK
    if os == "win": OK
    ERROR
  [Tests that mousemove events during pointer lock report correct button state]
    expected:
      if os == "win": PASS
      FAIL


[pointerlock-maintains-mousedown.html?unadjustedmovement=false]
  [Tests that mousemove events during pointer lock report correct button state]
    expected:
      if (os == "linux") and fission and not debug and not asan and tsan: [PASS, FAIL]
      if (os == "linux") and fission and not debug and asan: [PASS, FAIL]
      if (os == "linux") and not fission and debug: [FAIL, PASS]
      if (os == "linux") and not fission and not debug: [FAIL, PASS]
      if (os == "win") and debug: [PASS, FAIL]
      if os == "mac": FAIL
      if os == "android": FAIL
