[pointerlock_unadjustedMovement.html]
  [pointerlock_unadjustedMovement]
    expected:
      # Not every platform supports unadjusted movement.
      if os == "mac": PASS
      if os == "win": PASS
      FAIL
