[package]
name = "builtins-static"
version = "0.1.0"
authors = ["John Schanck <jschanck@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
pkcs11-bindings = "0.1.1"
smallvec = { version = "1.9.0", features = ["const_new"] }

[build-dependencies]
bindgen = { default-features = false, features = ["runtime"], version = "0.63" }
nom = "7.1.1"

[lib]
crate-type = ["staticlib"]
