/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(3201b705-0907-4f7c-aa9b-78bfeae52ed6)]
interface nsIFIPSUtils : nsISupports
{
  [must_use]
  readonly attribute boolean canToggleFIPS;

  [must_use]
  void toggleFIPSMode();

  [must_use]
  readonly attribute boolean isFIPSEnabled;
};
