/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISerialEventTarget.idl"
#include "nsISupports.idl"

%{C++
#define NS_PKCS11MODULEDB_CONTRACTID "@mozilla.org/security/pkcs11moduledb;1"
%}

[scriptable, uuid(ff9fbcd7-9517-4334-b97a-ceed78909974)]
interface nsIPKCS11ModuleDB : nsISupports
{
  [implicit_jscontext, must_use]
  Promise deleteModule(in AString moduleName);

  [implicit_jscontext, must_use]
  Promise addModule(in AString moduleName,
                    in AString libraryPath,
                    in unsigned long mechanismFlags,
                    in unsigned long cipherFlags);

  /**
   * Resolves with an array of nsIPKCS11Module describing the configured
   * PKCS#11 modules known to the module DB.
   */
  [implicit_jscontext, must_use]
  Promise listModules();
};
