# Configure UniFFI sources
#
# Each key is the UDL namespace of the component.
#
#
# IMPORTANT: Please Request review from a DOM peer before
# committing to using UniFFI. There are other ways to consume Rust from
# JavaScript that might fit your use case better.

# TODO: Upgrade the TOML crate and switch to array of tables syntax.


[suggest.async_wrappers]
# All functions/methods are wrapped to be async by default and must be `await`ed.
enable = true
# These are exceptions to the async wrapping.  These functions must not be `await`ed.
main_thread = [
  "raw_suggestion_url_matches",
  "SuggestStore",
  "SuggestStore.interrupt",
  "SuggestStoreBuilder",
  "SuggestStoreBuilder.data_path",
  "SuggestStoreBuilder.load_extension",
  "SuggestStoreBuilder.remote_settings_bucket_name",
  "SuggestStoreBuilder.remote_settings_server",
  "SuggestStoreBuilder.build",
]

[relevancy.async_wrappers]
# All functions/methods are wrapped to be async by default and must be `await`ed.
enable = true
# These are exceptions to the async wrapping.  These functions must not be `await`ed.
main_thread = [
  "RelevancyStore",
  "RelevancyStore.close",
  "RelevancyStore.interrupt",
  "score",
]

[remote_settings.async_wrappers]
# All functions/methods are wrapped to be async by default and must be `await`ed.
enable = true
# These are exceptions to the async wrapping.  These functions must not be `await`ed.
main_thread = [
  "RemoteSettings",
]

[error_support.async_wrappers]
# All functions/methods are wrapped to be async by default and must be `await`ed.
enable = true

[tabs.async_wrappers]
# All functions/methods are wrapped to be async by default and must be `await`ed.
enable = true

[arithmetical.async_wrappers]
enable = true

[uniffi_custom_types.async_wrappers]
enable = true

[uniffi_fixture_callbacks.async_wrappers]
enable = true
main_thread = [
  "log_even_numbers_main_thread",
]

[uniffi_fixture_external_types.async_wrappers]
enable = true

[uniffi_geometry.async_wrappers]
enable = true

[uniffi_rondpoint.async_wrappers]
enable = true

[uniffi_sprites.async_wrappers]
enable = true

[uniffi_todolist.async_wrappers]
enable = true
