# Configure UniFFI sources
#
# Each key is the UDL namespace of the component.
#
#
# IMPORTANT: Please Request review from a DOM peer before
# committing to using UniFFI. There are other ways to consume Rust from
# JavaScript that might fit your use case better.

# TODO: Upgrade the TOML crate and switch to array of tables syntax.

[sync15]
crate_name = "sync15"
udl_file = "third_party/rust/sync15/src/sync15.udl"

[tabs]
crate_name = "tabs"
udl_file = "third_party/rust/tabs/src/tabs.udl"

[suggest]
crate_name = "suggest"
udl_file = "third_party/rust/suggest/src/suggest.udl"

[suggest.receiver_thread]
default = "worker"
main = [
  "raw_suggestion_url_matches",
  "SuggestStore",
  "SuggestStore.interrupt",
]

[remote_settings]
crate_name = "remote_settings"
udl_file = "third_party/rust/remote_settings/src/remote_settings.udl"

[remote_settings.receiver_thread]
default = "worker"
main = [
  "RemoteSettings",
]

[geometry]
crate_name = "uniffi_geometry"
udl_file = "third_party/rust/uniffi-example-geometry/src/geometry.udl"
fixture = true

[arithmetic]
crate_name = "arithmetical"
udl_file = "third_party/rust/uniffi-example-arithmetic/src/arithmetic.udl"
fixture = true

[rondpoint]
crate_name = "uniffi_rondpoint"
udl_file = "third_party/rust/uniffi-example-rondpoint/src/rondpoint.udl"
fixture = true

[sprites]
crate_name = "uniffi_sprites"
udl_file = "third_party/rust/uniffi-example-sprites/src/sprites.udl"
fixture = true

[todolist]
crate_name = "uniffi_todolist"
udl_file = "third_party/rust/uniffi-example-todolist/src/todolist.udl"
fixture = true

[fixture_callbacks]
crate_name = "uniffi_fixture_callbacks"
udl_file = "toolkit/components/uniffi-fixture-callbacks/src/callbacks.udl"
fixture = true

[fixture_callbacks.receiver_thread]
default = "worker"
main = [
  "log_even_numbers_main_thread",
]

[custom_types]
crate_name = "uniffi_custom_types"
udl_file = "toolkit/components/uniffi-example-custom-types/src/custom-types.udl"
fixture = true

[external_types]
crate_name = "uniffi_fixture_external_types"
udl_file = "toolkit/components/uniffi-fixture-external-types/src/external-types.udl"
fixture = true
