# Maven group ID used for all components
componentsGroupId: "org.mozilla.components"

# Synchronized build configuration for all modules
jvmTargetCompatibility: 17
compileSdkMajorVersion: 37
compileSdkMinorVersion: 0
minSdkVersion: 26
targetSdkVersion: 36
