[package]
name = "gkrust"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"
description = "Rust code for libxul"

[dependencies]
gkrust-shared = { path = "shared" }
mozilla-central-workspace-hack = { path = "../../../build/workspace-hack" }

# Workarounds for https://github.com/rust-lang/rust/issues/58393
mozglue-static = { path = "../../../mozglue/static/rust" }
swgl = { path = "../../../gfx/wr/swgl" }
lmdb-rkv-sys = "0.11"

[dev-dependencies]
stylo_tests = { path = "../../../servo/ports/geckolib/tests/" }

[lib]
path = "lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false

[package.metadata.cargo-udeps.ignore]
normal = ["mozilla-central-workspace-hack"]
