[package]
name = "ipcclientcerts"
version = "0.1.0"
authors = ["Dana Keeler <dkeeler@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
byteorder = "1.3"
pkcs11-bindings = "0.1"
rsclientcerts = { path = "../rsclientcerts" }
sha2 = "0.10.2"
