/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(f905d1cc-9d34-423c-9e88-32247766e527)]
interface nsIMediaDrmProvisioning : nsISupports
{
  Promise provision(in AString aServerUrl, in AString aRequest);
};
