[package]
name = "fog"
version = "0.1.0"
authors = ["Glean SDK team <glean-team@mozilla.com>"]
edition = "2018"
publish = false

[dependencies]
bincode = "1.0"
chrono = "0.4.10"
ffi-support = "0.4"
glean = "33.4.0"
glean-core = { version = "33.4.0", features = ["rkv-safe-mode"] }
log = "0.4"
nsstring = { path = "../../../../xpcom/rust/nsstring", optional = true }
once_cell = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4"] }
xpcom = { path = "../../../../xpcom/rust/xpcom", optional = true }
thiserror = "1.0.4"
crossbeam-channel = "0.4.3"

[dev-dependencies]
tempfile = "3.1.0"

[features]
with_gecko = ["xpcom", "nsstring"]
