[package]
name = "mozglue-static"
version = "0.1.0"
edition = "2018"
license = "MPL-2.0"

[lib]
path = "lib.rs"

[dependencies]
arrayvec = "0.7"

[build-dependencies]
mozbuild = "0.1"
cc = "1"
rustc_version = "0.4"

[features]
moz_memory = []
