# Attempt to build the whole browser
name: Browser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Test complete build on Ubuntu
  ubuntu-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install Dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y   \
               curl                 \
               python3              \
               python3-pip          \
               python3-venv         \
               tar                  \
               zip                  \
               unzip                \
               git
          sudo apt-get install -y --no-install-recommends ffmpeg libasound2 libatk1.0-0 libcairo-gobject2 libcairo2 libdbus-1-3 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgdk-pixbuf-2.0-0 libglib2.0-0 libgtk-3-0 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 xvfb fonts-noto-color-emoji fonts-unifont xfonts-cyrillic xfonts-scalable fonts-liberation fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf fonts-freefont-ttf
          python3 -m pip install setuptools
          df -h

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Dry Run
        run: |
          df -h
          cp taintfox_mozconfig_ubuntu .mozconfig
          bash build.sh -p -n

      - name: Bootstrap
        run: |
          df -h
          bash build.sh -u -v

      - name: Build
        run: |
          df -h
          bash build.sh -s -v

      - name: Package
        run: |
          df -h
          bash build.sh -s -u

  # Test complete build on Windows
  windows-build:
    runs-on: windows-latest

    steps:

      - name: Download mozbuild
        run: |
          Set-PSDebug -Trace 1
          mkdir -p C:\mozilla-build
          cd C:\mozilla-build
          Invoke-WebRequest https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -OutFile .\MozillaBuildSetup-Latest.exe
          &'C:\Program Files\7-Zip\7z.exe' x -r -y .\MozillaBuildSetup-Latest.exe
          pwd
          ls
          cmd.exe /c 'C:\mozilla-build\start-shell.bat' --help
          where bash
          echo "ls -l /" | bash.exe
          rm -Recuse -Force "C:\mozilla-build\msys2"
          mklink /D "C:\msys64" "C:\mozilla-build\msys2"

      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          msystem: MSYS

      - name: Test Bash
        shell: bash
        run: |
          which bash
          echo "ls -l /" | bash
          echo "ls -l /tmp" | bash

      - name: Test Mozbuild
        shell: msys2 {0}
        run: |
          echo "Mozilla Build"
          ls -l /c/mozilla-build
          echo "Msys2"
          ls -l /c/mozilla-build/msys2/
          which bash
          echo "ls -l /" | bash
          echo "ls -l /tmp" | bash
          sh --help
          bash --help
  
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

#      - name: Bootstrap
#        run: |
#          cp "taintfox_mozconfig_win" ".mozconfig"        
#          .\mach.ps1  --no-interactive bootstrap --application-choice=browser
#      - name: Build
#        run: |
#          .\mach.ps1 build
#      - name: Package
#        run: |
#          .\mach.ps1 package
  
      - name: Bootstrap
        shell: msys2 {0}
        run: |
          export PATH=/c/mozilla-build/bin:/c/mozilla-build/python3:${PATH}
          export BASH=/usr/bin/bash
          ls -l /tmp
          mkdir -p /tmp
          ls -l /tmp
          cp "taintfox_mozconfig_win" ".mozconfig"
          ./mach --no-interactive bootstrap --application-choice=browser
    
#      - name: Build
#        shell: msys2 {0}
#        run: |
#          export PATH=${PATH}:/c/mozilla-build/python3
#          ./mach build
    
#      - name: Package
#        shell: msys2 {0}
#        run: |
#          export PATH=${PATH}:/c/mozilla-build/python3
#          ./mach package
