# Attempt to build the whole browser
name: Browser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Test applying playwright patches and installing dependencies
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y   \
               curl                 \
               python3              \
               python3-pip          \
               python3-venv         \
               tar                  \
               zip                  \
               unzip                \
               git
          python3 -m pip install setuptools

      - name: Checkout release branch
        uses: actions/checkout@v3

      - name: Dry Run
        run: |
          cp taintfox_mozconfig_ubuntu .mozconfig
          bash build.sh -p -n

      - name: Build
        run: |
          bash build.sh -s -v

      - name: Package
        run: |
          bash build.sh -s -u
