# Attempt to build the whole browser
name: Browser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Test applying playwright patches and installing dependencies
  patch:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y   \
               curl                 \
               python3              \
               python3-pip          \
               python3-venv         \
               tar                  \
               zip                  \
               unzip                \
               git
          sudo apt-get install -y --no-install-recommends ffmpeg libasound2 libatk1.0-0 libcairo-gobject2 libcairo2 libdbus-1-3 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgdk-pixbuf-2.0-0 libglib2.0-0 libgtk-3-0 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 xvfb fonts-noto-color-emoji fonts-unifont xfonts-cyrillic xfonts-scalable fonts-liberation fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf fonts-freefont-ttf
          python3 -m pip install setuptools
          df -h

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Dry Run
        run: |
          df -h
          cp taintfox_mozconfig_ubuntu .mozconfig
          bash build.sh -p -n

      - name: Bootstrap
        run: |
          df -h
          bash build.sh -u -v

      - name: Build
        run: |
          df -h
          bash build.sh -s -v

      - name: Package
        run: |
          df -h
          bash build.sh -s -u
