
name: JS Rooting Hazards

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    name: 'JS Rooting Hazard Analysis'

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true


      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y   \
               curl                 \
               python3              \
               python3-pip          \
               python3-venv         \
               tar                  \
               zip                  \
               unzip                \
               git
          sudo apt-get install -y --no-install-recommends ffmpeg libasound2 libatk1.0-0 libcairo-gobject2 libcairo2 libdbus-1-3 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgdk-pixbuf-2.0-0 libglib2.0-0 libgtk-3-0 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 xvfb fonts-noto-color-emoji fonts-unifont xfonts-cyrillic xfonts-scalable fonts-liberation fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf fonts-freefont-ttf
          python3 -m pip install setuptools


      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Bootstrap
        run: |
          ./mach --no-interactive bootstrap --application-choice=js

      - name: Bootstrap Hazard Analysis
        run: |
          ./mach hazards bootstrap
      
      - name: Build Shell
        run: |
          ./mach hazards build-shell

      - name: Gather GC Info
        run: |
          ./mach hazards gather --project=js

      - name: Analyze JS Hazards
        run: |
          ./mach hazards analyze --project=js

      - name: Show Summary
        run: |
          cat ./haz-js/hazards.txt >> $GITHUB_STEP_SUMMARY
      #- name: Upload Report
      #  uses: actions/upload-artifact@v4  # upload test results
      #  with:
      #    name: rooting-hazards
      #    path: haz-js/hazards.txt
