# This is a basic workflow to help you get started with Actions

name: Playwright

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Test applying playwright patches and installing dependencies
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
               apt-get install -y   \
               curl                 \
               python3              \
               python3-pip          \
               python3.10-venv      \
               tar                  \
               zip                  \
               unzip                \
               git                  \
               python3 -m pip install setuptools

      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: foxhound

      - name: Dry Run
        run: |
          cd foxhound
          bash -p -n   
    
      - name: Patch
        run: |
          cd foxhound
          bash -p -u -v
