name: 'Test Report'
on:
  workflow_run:
    workflows: ['Browser']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: foxhound-tests            # artifact name
        name: Foxhound Tests            # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
