name: 'Test Report JS Tests'
on:
  workflow_run:
    workflows: ['Browser']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: 'Add default settings to node calls'
        shell: bash
        run: |
          #
          # The later used dorny/test-reporter@v1 action can throw the following exception when enough tests have been
          # executed:
          #     RangeError: Maximum call stack size exceeded
          #
          # We explicitly increase the max. stack size here to workaround this issue.
          #

          which node
          node --version

          mv /usr/local/bin/node /usr/local/bin/node_org
          echo '#!/bin/bash' >> /usr/local/bin/node
          echo '/usr/local/bin/node_org --stack-size=2048 $@' >> /usr/local/bin/node
          cat /usr/local/bin/node
          chmod +x /usr/local/bin/node
      - uses: dorny/test-reporter@v2
        with:
          artifact: foxhound-tests            # artifact name
        name: MochiTests Tests            # Name of the check run which will be created
        path: 'taint_test_output.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
