# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'name': 'ScopedPrefsService',
        'cid': '{63a0e445-e1ff-41ef-9f8c-0af5b30f894c}',
        'interfaces': ['nsIScopedPrefs'],
        'contract_ids': ['@mozilla.org/scoped-prefs;1'],
        'type': 'mozilla::ScopedPrefs',
        'headers': ['/toolkit/components/antitracking/scopedprefs/ScopedPrefs.h'],
    },
]
