[package]
edition = "2015"
name = "mime-guess-ffi"
version = "0.1.0"
license = "MPL-2.0"
authors = ["The Mozilla Project Developers"]

[dependencies]
mime_guess = "2.0.4"
nserror = { path = "../../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../../xpcom/rust/nsstring" }
